### ISSUE TITLE
Details on using this service as a github action are lacking on details

### ISSUE THREAD

**Issue by justinperkins** [ayan-b/gist-todo-list-action#3]
I'm reading the [documentation here](https://github.com/ayan-b/gist-todo-list-action#using-with-github-action) and I really can't make heads or tails on what I'm supposed to do. The instructions say that I don't need to fork the repo, but the marketplace instructions talk about a YAML file. Where does this YAML file live?

**Comment by ayan-b** [comment]
This is your GitHub Actions workflow file. Check this [one](https://github.com/ayan-b/playground/blob/master/.github/workflows/todo-action.yaml) for example.

**Comment by tacovoyager** [comment]
Thanks @ayan-b, am I interpreting this correctly that I should create a random repo to house my personal GitHub Actions workflow file and that's where I add `todo-action.yaml`?

**Comment by ayan-b** [comment]
Hi @justinperkins, yes, that's correct.
